# Gems
gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: 블로그 제목
subtitle: "블로그 소제목"
email: tsi00008@gmail.com
name: ivoryRabbit
description:
  Rlog - Research Blog

baseurl: ""
url: "http://ivoryRabbit.github.io"
cover: "/assets/coffe.jpg"
logo: "/assets/bunny.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: my-github-blog-3

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options

social:
  - name: Facebook
    icon: facebook
    username: Facebook
    url: https://www.facebook.com/
    desc: Friend me on Facebook
    share: false

  - name: GitHub
    icon: github
    username: ivoryRabbit
    url: https://github.com/ivoryRabbit
    desc: GitHub
    share: true

  - name: LinkedIn
    icon: linkedin
    username: ivoryRabbit
    url: 
    desc: Connect with me on LinkedIn
    share: false

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: false
